version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/storage:/app/storage
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
      - BACKEND_DEBUG=false
      - STORAGE_PATH=/app/storage
      - RAW_DOCS_PATH=/app/storage/raw
      - INDEX_PATH=/app/storage/index
      - CHROMA_PERSIST_DIRECTORY=/app/storage/chroma
      - PLAYWRIGHT_HEADLESS=true
    depends_on:
      - chroma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - ./backend/storage/chroma:/chroma/chroma
    ports:
      - "8001:8000"
    environment:
      - ALLOW_RESET=true
      - CHROMA_DB_IMPL=duckdb+parquet
      - PERSIST_DIRECTORY=/chroma/chroma 